baseURL = "https://mathanamathav.github.io/"
languageCode = "en-us"
title = "Mathan"
theme = "hugo-bearblog"

[params]
  description = "Developer."
  dateFormat = "2006-01-02"
  hideMadeWithLine = true

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/cv/"
  weight = 3

[caches]
  [caches.images]
    dir = ":cacheDir/images"
